services:
    api:
        image: python:3.8
        #user: $(id -u ${USER}):$(id -u ${USER}) #root
        container_name: vanda_client_redis
        ipc: host
        tty: true
        volumes:
            - $PWD:/usr/src/myapp/
        environment:
            - REDIS_HOST={{ redis_host | default('localhost') }}
            - REDIS_PORT={{ redis_port | default(6379) }}
            - REDIS_DB={{ redis_db | default(0) }}
            - REDIS_PASSWORD={{ redis_password }}
        working_dir: /usr/src/myapp/
        # command: /bin/sh -c "while true; do sleep 5m; done"
        command: /bin/sh -c "cd /usr/src/myapp/ && pip3 install -r requirements.txt && python3 main.py"
        restart: unless-stopped     # or "always"

{% if redis_network %}
networks:
    default:
        external:
            name: {{ redis_network }}
{% endif %}
